### ISSUE TITLE
Decreased rank Attack not working

### ISSUE THREAD

**Issue by Bushra4** [crond-jaist/iotrain-sim#1]
Decreased Rank attack is working like without any attack. Do we have to do some more changings?

**Comment by crond-jaist** [comment]
Hi,
I'm sorry to hear that the decreased rank attack did not work for you. The student who created this training content mentioned once that occasionally the attack results don't look as expected, and he suggested to run the experiment again. So could you run again your experiment and see what happens? If this still fails, you could perhaps try to extend the simulation time...
Best wishes,
Razvan

**Comment by Bushra4** [comment]
I have reloaded the simulation but the results are same.

**Comment by crond-jaist** [comment]
Hi,
I am sorry to hear that your simulation results are still not as you expect. Unfortunately, we don't currently have the human resources to look into this in more detail now. If you ever find out a solution, please let us know. I may be able to investigate this issue in a couple of months, but I cannot promise anything at this time.
Best wishes,
Razvan
